services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    depends_on:
      - backend
    networks:
      - appnet
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
