services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    depends_on:
      - backend
    networks:
      - appnet
    volumes:
      - ./frontend:/app # bind mount
      - /app/node_modules   # anonymous volume for container's node_modules
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - appnet
    volumes:
      - ./backend:/app # bind mount
      - /app/node_modules  # anonymous volume for container's node_modules
      - sqlite-data:/app/data
networks:
  appnet:
    driver: bridge

volumes:
  sqlite-data: 
